objects = Variables.o BC_Supersonic.o BC_Supersonic_New.o BC_Supersonic_Temp.o Derivatives.o Flux_U.o Freestream.o Grid.o Invicid_X_fluxes.o Invicid_Y_fluxes.o Swap.o Time_Step.o Update.o Viscous_Properties.o WAG.o IDS.o Restart_Files.o DynamicArrays.o Upper_vis_bc.o Upper_vis_in.o Viscous_X_fluxes.o Viscous_Y_fluxes.o Lower_vis_bc.o Lower_vis_in.o L_vis_bc.o L_vis_in.o R_vis_bc.o R_vis_in.o Transient_Output.o Output.o
FC = gfortran
FFLAGS = -O3
FFLAGSDEBUG =
PPARALLEL =  -fopenmp
IDS: $(objects)
	$(FC) -o IDS $(FFLAGS) $(PPARALLEL) $(objects)
variables.mod: Variables.o Variables.f90
	$(FC) -c Variables.f90
%.o : %.f90 variables.mod
	$(FC) -c $(FFLAGS) $(PPARALLEL) $<

# This section erases the files generated by the makefile.
clean:
	rm $(objects)
	rm variables.mod IDS
